/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'admin'
const service = ''
const gateway = 'default'

export const AdminController = {
  // 创建管理员
  createAdmin: {
    gateway,
    service,
    controller,
    path: '/api/admin/admin',
    action: 'createAdmin',
    type: RequestMethod.Post,
  },
  // 查询管理员列表
  findAdmin: {
    gateway,
    service,
    controller,
    path: '/api/admin/admin',
    action: 'findAdmin',
    type: RequestMethod.Get,
  },
  // 更新管理员
  updateAdmin: {
    gateway,
    service,
    controller,
    path: '/api/admin/admin/{id}',
    action: 'updateAdmin',
    type: RequestMethod.Put,
  },
  // 获取管理员
  getAdmin: {
    gateway,
    service,
    controller,
    path: '/api/admin/admin/{id}',
    action: 'getAdmin',
    type: RequestMethod.Get,
  },
  // 删除用户
  removeAdmin: {
    gateway,
    service,
    controller,
    path: '/api/admin/admin/{id}',
    action: 'removeAdmin',
    type: RequestMethod.Delete,
  },
  // 重置管理员密码
  resetAdminPassword: {
    gateway,
    service,
    controller,
    path: '/api/admin/admin/reset-password/{id}',
    action: 'resetAdminPassword',
    type: RequestMethod.Patch,
  },
  // 更新管理员密码
  updateAdminPassword: {
    gateway,
    service,
    controller,
    path: '/api/admin/admin/update-password/{id}',
    action: 'updateAdminPassword',
    type: RequestMethod.Patch,
  },
}
