/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'administrator'
const service = ''
const gateway = 'default'

export const AdministratorController = {
  // 创建管理员
  createAdministrator: {
    gateway,
    service,
    controller,
    path: '/api/admin/administrator',
    action: 'createAdministrator',
    type: RequestMethod.Post,
  },
  // 查询管理员列表
  findAdministrator: {
    gateway,
    service,
    controller,
    path: '/api/admin/administrator',
    action: 'findAdministrator',
    type: RequestMethod.Get,
  },
  // 更新管理员
  updateAdministrator: {
    gateway,
    service,
    controller,
    path: '/api/admin/administrator/{id}',
    action: 'updateAdministrator',
    type: RequestMethod.Put,
  },
  // 获取管理员
  getAdministrator: {
    gateway,
    service,
    controller,
    path: '/api/admin/administrator/{id}',
    action: 'getAdministrator',
    type: RequestMethod.Get,
  },
  // 删除用户
  removeAdministrator: {
    gateway,
    service,
    controller,
    path: '/api/admin/administrator/{id}',
    action: 'removeAdministrator',
    type: RequestMethod.Delete,
  },
  // 重置管理员密码
  resetAdministratorPassword: {
    gateway,
    service,
    controller,
    path: '/api/admin/administrator/reset-password/{id}',
    action: 'resetAdministratorPassword',
    type: RequestMethod.Patch,
  },
  // 更新管理员密码
  updateAdministratorPassword: {
    gateway,
    service,
    controller,
    path: '/api/admin/administrator/update-password/{id}',
    action: 'updateAdministratorPassword',
    type: RequestMethod.Patch,
  },
}
