/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */

// 控制器名称
const controller = 'app'
const service = ''
const gateway = 'default'

export const AppController = {
  // 系统初始化
  appInit: {
    gateway,
    service,
    controller,
    path: '/api/admin/app/app-init',
    action: 'appInit',
    type: RequestMethod.Post,
  },
  // 获取系统基本信息
  appBase: {
    gateway,
    service,
    controller,
    path: '/api/admin/app/app-base',
    action: 'appBase',
    type: RequestMethod.Get,
  },
  // 管理员登录
  login: {
    gateway,
    service,
    controller,
    path: '/api/admin/app/login',
    action: 'login',
    type: RequestMethod.Post,
  },
  // 刷新Token
  token: {
    gateway,
    service,
    controller,
    path: '/api/admin/app/token',
    action: 'token',
    type: RequestMethod.Get,
  },
  // 获取当前用户信息
  getCurrentAdmin: {
    gateway,
    service,
    controller,
    path: '/api/admin/app/current',
    action: 'getCurrentAdmin',
    type: RequestMethod.Get,
  },
}
