/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */

// 控制器名称
const controller = 'product'
const service = ''
const gateway = 'default'

export const ProductController = {
  // 查询商品
  findProduct: {
    gateway,
    service,
    controller,
    path: '/api/admin/product',
    action: 'findProduct',
    type: RequestMethod.Get,
  },
  // 创建商品
  createProduct: {
    gateway,
    service,
    controller,
    path: '/api/admin/product',
    action: 'createProduct',
    type: RequestMethod.Post,
  },
  // 获取商品
  getProduct: {
    gateway,
    service,
    controller,
    path: '/api/admin/product/{id}',
    action: 'getProduct',
    type: RequestMethod.Get,
  },
  // 更新商品
  updateProduct: {
    gateway,
    service,
    controller,
    path: '/api/admin/product/{id}',
    action: 'updateProduct',
    type: RequestMethod.Put,
  },
  // 删除商品
  deleteProduct: {
    gateway,
    service,
    controller,
    path: '/api/admin/product/{id}',
    action: 'deleteProduct',
    type: RequestMethod.Delete,
  },
}
