/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */

// 控制器名称
const controller = 'qiniu'
const service = ''
const gateway = 'default'

export const QiniuController = {
  //
  getUploadToken: {
    gateway,
    service,
    controller,
    path: '/api/qiniu/upload-token',
    action: 'getUploadToken',
    type: RequestMethod.Get,
  },
}
