// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACard: typeof import('@arco-design/web-vue')['Card']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AImage: typeof import('@arco-design/web-vue')['Image']
    AImagePreviewGroup: typeof import('@arco-design/web-vue')['ImagePreviewGroup']
    AInput: typeof import('@arco-design/web-vue')['Input']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    AOption: typeof import('@arco-design/web-vue')['Option']
    APopconfirm: typeof import('@arco-design/web-vue')['Popconfirm']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    ATable: typeof import('@arco-design/web-vue')['Table']
    ATableColumn: typeof import('@arco-design/web-vue')['TableColumn']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    ATreeSelect: typeof import('@arco-design/web-vue')['TreeSelect']
    'IconPark:menuFold': typeof import('~icons/icon-park/menu-fold')['default']
    'IconPark:menuUnfold': typeof import('~icons/icon-park/menu-unfold')['default']
    'IconPark:plus': typeof import('~icons/icon-park/plus')['default']
    'IconPark:sortAmountDown': typeof import('~icons/icon-park/sort-amount-down')['default']
    'IconParkOutline:delete': typeof import('~icons/icon-park-outline/delete')['default']
    ImagePreview: typeof import('./../shared/components/image-preview.vue')['default']
    MediaGallery: typeof import('./../shared/components/media-gallery.vue')['default']
    MediaGalleryItem: typeof import('./../shared/components/media-gallery-item.vue')['default']
    PageContainer: typeof import('./../shared/components/page-container.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadContainer: typeof import('./../shared/components/upload-container.vue')['default']
    UploadProgress: typeof import('./../shared/components/upload-progress.vue')['default']
    VideoPreview: typeof import('./../shared/components/video-preview.vue')['default']
  }
}
