/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { AdminController } from '~/http/controllers/admin.controller'
import { Admin, AdminResetPasswordResponse } from '~/http/model'

export class AdminService {
  /**
   * 创建管理员
   */
  @Request({
    server: AdminController.createAdmin,
    model: Admin,
  })
  public createAdmin(
    params?: RequestParams | { [key: string]: any },
  ): Observable<Admin> {
    return RequestParams.create(params).request()
  }
  /**
   * 查询管理员
   */
  @Request({
    server: AdminController.findAdmin,
    model: Admin,
  })
  public findAdmin(
    params?: RequestParams | { [key: string]: any },
  ): Observable<Admin[]> {
    return RequestParams.create(params).request()
  }
  /**
   * 更新管理员
   */
  @Request({
    server: AdminController.updateAdmin,
    model: Admin,
  })
  public updateAdmin(
    params?: RequestParams | { [key: string]: any },
  ): Observable<Admin> {
    return RequestParams.create(params).request()
  }
  /**
   * 获取管理员
   */
  @Request({
    server: AdminController.getAdmin,
    model: Admin,
  })
  public getAdmin(
    params?: RequestParams | { [key: string]: any },
  ): Observable<Admin> {
    return RequestParams.create(params).request()
  }
  /**
   * 删除用户
   */
  @Request({
    server: AdminController.removeAdmin,
  })
  public removeAdmin(
    params?: RequestParams | { [key: string]: any },
  ): Observable<any> {
    return RequestParams.create(params).request()
  }
  /**
   * 重置管理员密码
   */
  @Request({
    server: AdminController.resetAdminPassword,
    model: AdminResetPasswordResponse,
  })
  public resetAdminPassword(
    params?: RequestParams | { [key: string]: any },
  ): Observable<AdminResetPasswordResponse> {
    return RequestParams.create(params).request()
  }
  /**
   * 更新管理员密码
   */
  @Request({
    server: AdminController.updateAdminPassword,
  })
  public updateAdminPassword(
    params?: RequestParams | { [key: string]: any },
  ): Observable<any> {
    return RequestParams.create(params).request()
  }
}
