/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { BannerController } from '~/http/controllers/banner.controller'
import { Banner } from '~/http/model'

export class BannerService {
  /**
   * 创建Banner
   */
  @Request({
    server: BannerController.createBanner,
    model: Banner
  })
  public createBanner(
    params?: RequestParams | { [key: string]: any }
  ): Observable<Banner> {
    return RequestParams.create(params).request();
  }
  /**
   * 查询Banner列表
   */
  @Request({
    server: BannerController.findBanner,
    model: Banner
  })
  public findBanner(
    params?: RequestParams | { [key: string]: any }
  ): Observable<Banner[]> {
    return RequestParams.create(params).request();
  }
  /**
   * 更新Banner
   */
  @Request({
    server: BannerController.updateBanner,
    model: Banner
  })
  public updateBanner(
    params?: RequestParams | { [key: string]: any }
  ): Observable<Banner> {
    return RequestParams.create(params).request();
  }
  /**
   * 获取Banner
   */
  @Request({
    server: BannerController.getBanner,
    model: Banner
  })
  public getBanner(
    params?: RequestParams | { [key: string]: any }
  ): Observable<Banner> {
    return RequestParams.create(params).request();
  }
  /**
   * 删除Banner
   */
  @Request({
    server: BannerController.removeBanner,
  })
  public removeBanner(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
  /**
   * 交换Banner位置
   */
  @Request({
    server: BannerController.changeBannerOrder,
  })
  public changeBannerOrder(
    params?: RequestParams | { [key: string]: any }
  ): Observable<any> {
    return RequestParams.create(params).request();
  }
}
