/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { MaterialController } from '~/http/controllers/material.controller'
import { Material, MaterialGroupResponse } from '~/http/model'

export class MaterialService {
  /**
   * 创建素材
   */
  @Request({
    server: MaterialController.createMaterial,
    model: Material,
  })
  public createMaterial(
    params?: RequestParams | { [key: string]: any },
  ): Observable<Material[]> {
    return RequestParams.create(params).request()
  }
  /**
   * 获取素材列表
   */
  @Request({
    server: MaterialController.findMaterial,
    model: Material,
  })
  public findMaterial(
    params?: RequestParams | { [key: string]: any },
  ): Observable<Material[]> {
    return RequestParams.create(params).request()
  }
  /**
   * 删除素材
   */
  @Request({
    server: MaterialController.deleteMaterialBatch,
  })
  public deleteMaterialBatch(
    params?: RequestParams | { [key: string]: any },
  ): Observable<any> {
    return RequestParams.create(params).request()
  }
  /**
   * 获取素材分组
   */
  @Request({
    server: MaterialController.findMaterialGroup,
    model: MaterialGroupResponse,
  })
  public findMaterialGroup(
    params?: RequestParams | { [key: string]: any },
  ): Observable<MaterialGroupResponse[]> {
    return RequestParams.create(params).request()
  }
  /**
   * 创建素材分组
   */
  @Request({
    server: MaterialController.createMaterialGroup,
    model: Material,
  })
  public createMaterialGroup(
    params?: RequestParams | { [key: string]: any },
  ): Observable<Material> {
    return RequestParams.create(params).request()
  }
  /**
   * 更新素材分组
   */
  @Request({
    server: MaterialController.updateMaterialGroup,
    model: Material,
  })
  public updateMaterialGroup(
    params?: RequestParams | { [key: string]: any },
  ): Observable<Material> {
    return RequestParams.create(params).request()
  }
  /**
   * 删除素材分组
   */
  @Request({
    server: MaterialController.deleteMaterialGroup,
    model: Material,
  })
  public deleteMaterialGroup(
    params?: RequestParams | { [key: string]: any },
  ): Observable<Material> {
    return RequestParams.create(params).request()
  }
  /**
   * 修改素材分组
   */
  @Request({
    server: MaterialController.changeGroupBatch,
  })
  public changeGroupBatch(
    params?: RequestParams | { [key: string]: any },
  ): Observable<any> {
    return RequestParams.create(params).request()
  }
}
