/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { ProductController } from '~/http/controllers/product.controller'
import { Product } from '~/http/model'

export class ProductService {
  /**
   * 查询商品
   */
  @Request({
    server: ProductController.findProduct,
    model: Product,
  })
  public findProduct(
    params?: RequestParams | { [key: string]: any },
  ): Observable<Product[]> {
    return RequestParams.create(params).request()
  }
  /**
   * 创建商品
   */
  @Request({
    server: ProductController.createProduct,
    model: Product,
  })
  public createProduct(
    params?: RequestParams | { [key: string]: any },
  ): Observable<Product> {
    return RequestParams.create(params).request()
  }
  /**
   * 获取商品
   */
  @Request({
    server: ProductController.getProduct,
    model: Product,
  })
  public getProduct(
    params?: RequestParams | { [key: string]: any },
  ): Observable<Product> {
    return RequestParams.create(params).request()
  }
  /**
   * 更新商品
   */
  @Request({
    server: ProductController.updateProduct,
    model: Product,
  })
  public updateProduct(
    params?: RequestParams | { [key: string]: any },
  ): Observable<Product> {
    return RequestParams.create(params).request()
  }
  /**
   * 删除商品
   */
  @Request({
    server: ProductController.deleteProduct,
  })
  public deleteProduct(
    params?: RequestParams | { [key: string]: any },
  ): Observable<any> {
    return RequestParams.create(params).request()
  }
}
