/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { QiniuController } from '~/http/controllers/qiniu.controller'
import { GetUploadTokenResponse } from '~/http/model'

export class QiniuService {
  /**
   *
   */
  @Request({
    server: QiniuController.getUploadToken,
    model: GetUploadTokenResponse,
  })
  public getUploadToken(
    params?: RequestParams | { [key: string]: any },
  ): Observable<GetUploadTokenResponse> {
    return RequestParams.create(params).request()
  }
}
