name: deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: build
        run: npm run build 
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: 121.5.165.149
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: rm -rf /usr/share/nginx/html/mall-admin.gopowerteam.cn/*
      - name: deploy
        uses: nogsantos/scp-deploy@master
        with:
          src: ./dist/*
          host: 121.5.165.149
          remote: /usr/share/nginx/html/mall-admin.gopowerteam.cn
          port: 22
          user: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}